[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "persevera_arbitrage"
version = "0.3.1"
description = "Statistical arbitrage tools for Persevera Asset Management"
authors = [{ name = "Persevera Asset Management" }]